service: exampleSls
provider:
  name: aws
  region: eu-central-1
functions:
  hello:
    handler: index.myFunc
    events:
      - http:
          path: /myFunc
          method: get
          integration: lambda
    vpc:
      securityGroupIds:
        - sg-fe330495
      subnetIds:
        - subnet-8c7c6ce4
        - subnet-f4d98a8e